# ALTERE COM OS DADOS DO SEU PROJETO E BANCO DE DADOS
spring.application.name=StockMaster
# Porta em que a aplicacao Spring Boot sera executada.
server.port=8080
# Cuidado com caracteres especiais na senha, como '#', etc.
# Quando usar o pooler de conexoes, incluir o parametro 'prepareThreshold=0' para evitar problemas de preparacao de consultas.
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.mvjdicbyslolxunwkbux&password=OSoJtIal2IEHilOS&prepareThreshold=0
# Esquema de criacao do banco de dados: 'create' para criar as tabelas a cada execucao, 'update' para atualizar o esquema.
spring.jpa.hibernate.ddl-auto=update
# Exibe as consultas SQL no console para depuracao.
spring.jpa.show-sql=true
# Define o dialeto do Hibernate para PostgreSQL, garantindo compatibilidade com as funcionalidades especificas do banco de dados.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


sa